include ./one-dark-pro-theme/themes/OneDark-Pro-darker.conf

symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 PowerlineSymbols

font_size 10.0
# font_family family="Liberation Mono" style="Regular"


# BEGIN_KITTY_FONTS
font_family      family="Liberation Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

scrollback_pager vim -u NONE -
  \ -c 'w! /tmp/kitty_scrollback' 
  \ -c 'term ++curwin cat /tmp/kitty_scrollback'
  \ -c "set clipboard=unnamedplus"
  \ -c "hi Normal ctermbg=235"
  \ -c "nnoremap Y y$"
  \ -c "tnoremap i ZQ"


map kitty_mod+i show_scrollback
map kitty_mod+u scroll_page_up
map kitty_mod+b scroll_page_down

map kitty_mod+] next_tab
map kitty_mod+[ previous_tab

tab_bar_style powerline
shell_integration no-title
